### ISSUE TITLE
Docker-spesific working directory breaks other tools

### ISSUE THREAD

**Issue by Bnaya** [Borales/actions-yarn#17]
The yarn commands are ran with the docker-internal working directory.
tools as jest, using these paths in some generated output, as lconv coverage reports,
And tools that run outside of the docker, on tasks after the yarn tasks get files paths they don't know

**Comment by Bnaya** [comment]
See https://github.com/coverallsapp/github-action/issues/21
that was very painful to debug, maybe add any warning on the readme?

**Comment by Borales** [comment]
@Bnaya Hi. This action was written for the Actions Beta (when Docker was probably the only way of running things for Actions), and a lot has changed since then. 
Please check the official https://github.com/actions/setup-node (which exposes Yarn as well).

This repo is mostly for supporting the pipelines with the old dataflow.
