### ISSUE TITLE
Issue with puppeteer and size-limit

### ISSUE THREAD

**Issue by igorkamyshev** [Borales/actions-yarn#7]
Hello! Great solution, it is very usefull.

I found one minor bug: this action fall, if I try to use size-limit (puppeteer inside).

Error log:
```
/github/workspace/node_modules/puppeteer/.local-chromium/linux-662092/chrome-linux/chrome: error while loading shared libraries: libX11-xcb.so.1: cannot open shared object file: No such file or directory
```

I guess, we can fix it by installation `libX11-xcb` in container.

What do you think?

**Comment by Borales** [comment]
@igorkamyshev hi, thank you for this ticket.

The purpose of this "action" is to provide base support for Yarn.
For example, if your project triggers some internal scripts to compile SASS files (via external `sass` lib dependency) via yarn - I cannot add it to this image either since a single Docker image cannot contain any possible dependency.

So in your case, I'd recommend building your own image using https://cloud.docker.com/u/borales/repository/docker/borales/yarn as a base and install your required libs. And you could still use the original yarn commands as described in README

**Comment by igorkamyshev** [comment]
Thanks for response!
